### ISSUE TITLE
Power function using recursion

### ISSUE THREAD

**Issue by impulse15** [impulse15/Hack-the-inner-you#1]
Make a code to find power of a number a^b. Take user input.

**Comment by Sukhamjot-Singh** [comment]
Can I work on this issue.
Which language do I need to write the code in?

**Comment by khushi-parikh** [comment]
may i work on this issue? i can code this in C and python.

**Comment by electricsohan** [comment]
please bhai assign kardo

**Comment by impulse15** [comment]
yeh mere bhai @electricsohan ke liye banaya hai, aap logo ko chahiye toh aur issue generate karta.
